// // // // // // // // // const name = "nizam"
// // // // // // // // // console.log(name)
// // // // // // // // // name = "salman"
// // // // // // // // // console.log(name)

// // // // // // // // name = "salman"
// // // // // // // // console.log(name)
// // // // // // // // let a = 4;
// // // // // // // // let b = 5;
// // // // // // // // console.log(a+b)
// // // // // // // // console.log(a**b)
// // // // // // // // console.log(a-b)
// // // // // // // // console.log(a/b)
// // // // // // // // console.log(a%b)
// // // // // // // // ------------concatenation and scope of a varaible -------------
// // // // // // // // console.log("my name is nizam ur rehman")
// // // // // // // // {let firstName = "nizam"
// // // // // // // // var lastName = "rehman"
// // // // // // // // console.log(firstName+" " + lastName);}
// // // // // // // // console.log(lastName)
// // // // // // // // let a = 4.67;
// // // // // // // // ceil = Math.ceil(a)
// // // // // // // // console.log(ceil);
// // // // // // // // // floor = Math.floor(a)
// // // // // // // // let  a = "10"
// // // // // // // // let b = "20"
// // // // // // // //  res = a+b;
// // // // // // // //  console.log(typeof res,res);
// // // // // // // let a = 20;
// // // // // // // let b = "30"
// // // // // // // let c = a+b
// // // // // // // console.log(typeof c,c);
// // // // // // let a = 20;
// // // // // // let b = "30"
// // // // // // // let c = a*b;
// // // // // // // console.log(typeof c,

// // // // // // // let d = a===b;
// // // // // // // console.log(d);
// // // // // // let d = a!=b;
// // // // // // console.log(d);
// // // // // // let minPurchase = 200;
// // // // // // let orderamt = 160
// // // // // // let disc = 20
// // // // // // eligfordisc = orderamt >= minPurchase ;
// // // // // // console.log(eligfordisc);
// // // // // // let oderamount = 100;

// // // // // // if (oderamount>50 &&>60) { console.log("20% discount is granted")
// // // // // // if (oderamount > 200) {
// // // // // //   console.log(" 20% discount");
// // // // // // } else if ((oderamount  = 100)) {
// // // // // //   console.log(" 5% discount is granted ");
// // // // // // } else {
// // // // // //   console.log(" no discount");
// // // // // // }

// // // // // // if (true) { console.log(" statement one exicuted");

// // // // // // }if (true) { console.log(" statement two exicuted ");

// // // // // // }if (false) { console.log(" statement not exicuted ");

// // // // // // }

// // // // // let q = 10;
// // // // //  let s =  q+1,
// // // // // while (condition) {

// // // // // // }(s <= 20) { console.log(" hello")
// // // // // //     s++;

// // // // // // }

// // // // //  ........ASSIGMENT NO. 1................
// // // // //  console.log(" NIZAM ");
// // // // //  console.log(" AGE : 20");
// // // // //  console.log( " MY FAV COLOR IS GREEN");

// // // // //  -----ASSIGMENT NUMBER 2 -------------

// // // // ;let a = 45;
// // // // ; let b = 23;
// // // //  let c  = 12;
// // // //  let d = 13;
// // // //  let e = 43;
// // // //  let f = a+b+c+d+e;
// // // //  console.log(" marks in english",a);
// // // //  console.log(" marks in science", b);
// // // //  console.log(" marks in math ",c);
// // // //  console.log("marks in zoology", d );
// // // //  console.log(" marks in biology", e );
// // // //  console.log("avg marks in total", f/5);

// // // //  --------------assigment number 3 -------------
// // // //  conversion of celsius to farenhiet

// // // // let f=10;
// // // // let celsius = 5/9*f-32;

// // // // {console.log(" farenhiet", celsius);

// // // // ----------------assigment number 4 -------------

// // // // let b= ;
// // // // if (b%2==0) { console.log(b,"is even number ");

// // // // }else{ console.log(b," is odd number");
// // // // }

// // // //  -----------ASSIGMENT NUMBER 5 -------------

// // // // let age = 21;
// // // // if (age>=18) { console.log(" person is eligible for vote ");

// // // // }else{ console.log(" person is not eligible for vote");
// // // // }

// // // // -------------- ASSIGMENT NUMBER 5 --------------
// // // // let a = 0;
// // // // if (a>0)  {console.log((a)," is a positive number");

// // // // }if (a ===0) { console.log(" this is a zero number ");

// // // // } if (a<0) {

// // // // } if(a<0){ console.log((a)," is a negative number ");}

// // // //  ----------- PRINT NUMBERS FROM 1 TO 50 -----------------

// // // // let x= 0;
// // // // let y = x+1;
// // // // while ( y<= 50) { console.log(y);
// // // //  y++

// // // // }

// // // // let x = 6;
// // // // let c = 1;
// // // // // let y =x*c;
// // // // while (c <= 10) {
// // // //   console.log(x * c);
// // // //   c++;
// // // // }

// // // //   let x= 0;
// // // //   let count = 0;

// // // //   while (x<= 200) {

// // // //     if (x%3==0 && x%5==0) {console.log(x);
// // // //     count++

// // // //     }
// // // //     x++;
// // // //   }
// // // //   {console.log("total numbers are ",count);}

// // // // let x = 1;
// // // // let sum = 0;
// // // // while(x<=100){

// // // //     // console.log(x);
// // // //     sum = sum + x;
// // // //     x++

// // // // }
// // // // console.log(sum);

// // // // let sum = 0;

// // // // for (let x = 1; x <= 20; x++) {
// // // //   if (x % 2 == 0) {
// // // //     // console.log(x);
// // // //     sum += x;
// // // //   }
// // // // }

// // // // console.log(sum);

// // // // let bag = "";

// // // // for(let i=1; i<=5; i++){
// // // //     bag = bag + i + " ";
// // // // }

// // // // console.log(bag);

// // // // Reverse Loop(while):
// // // // let i = 10;

// // // // while (i >= 1) {
// // // //   console.log("Value" + " " + i);
// // // //   i--;
// // // // }

// // // // Reverse Loop(for):
// // // // for (let i = 10; i >= 1; i--) {
// // // //   console.log("Value" + " " + i);
// // // // }

// // // // Factorial of a number:
// // // // 5! => 5*4*3*2*1

// // // // let i = 5;
// // // // let res = 1;
// // // // while(i >= 1){
// // // //     res = res * i;
// // // //     i--;
// // // // }
// // // // console.log(res);

// // // // let res = 1;
// // // // for (let x = 1; x <= 5; x++) {
// // // //   res = res * x;
// // // // }
// // // // console.log(res);

// // // // let i = 1;
// // // // while (i <= 10) {
// // // //   if (i > 5) {
// // // //     break;
// // // //   }
// // // //   console.log(i);
// // // //   i++;
// // // // }

// // // // let sum = 0;

// // // // for (let i = 1; i <= 20; i++) {
// // // //   if (sum >= 30) {
// // // //     break;
// // // //   }
// // // //   sum += i;
// // // // }

// // // // console.log(sum);

// // // // let sum = 0;
// // // // for (let x = 1; x <= 10; x++) {
// // // //   if (x > 7) {
// // // //     break;
// // // //   }
// // // //   sum = sum + x;
// // // // }
// // // // console.log(sum);

// // // // for (let i = 1; i <= 20; i++) {
// // // //   if (i % 7 === 0) {
// // // //     break;
// // // //   }
// // // //   console.log(i);
// // // // }

// // // // for (let i = 0; i < 5; i++) {
// // // //   break;
// // // //   console.log(i);
// // // // }
// // // // /
// // // // for (let i = 10; i > 0; i--) {
// // // //   if (5 > i) {
// // // //     break;
// // // //   }
// // // //   console.log(i);
// // // // }

// // // // for (let x = 1; x < 20; x++) {
// // // //   if (x > 10) {
// // // //     break;
// // // //   }
// // // //   console.log(x);
// // // // }

// // // // for (let x = 1; x <= 5; x++) {
// // // //   if (x === 3 || x === 4) {
// // // //     continue;
// // // //   }

// // // //   console.log(x);
// // // // }

// // // // let i = 1;

// // // // while (i <= 5) {
// // // //   if (i === 3) {
// // // //     continue;
// // // //   }
// // // //   console.log(i);
// // // //   i++;
// // // // }

// // // // for (let i = 1; i <= 20; i++) {
// // // //   if (i >= 5 && i <= 10) {
// // // //     continue;
// // // //   }
// // // //   console.log(i);
// // // // }

// // // //  -------------arrays----------------

// // // // ---------HOW TO CHECK NO OF VARAIBLES

// // // // let array = [" gousia ", " nizam ","salman"," moomin"]
// // // // console.log(array.length);

// // // // ----------HOW TO CHECK VALUE AT PARTICULAR POSITION----------

// // // // let array = [" gousia ", " nizam ","salman"," moomin"]
// // // // console.log(array[1]);

// // // // ----------how to pop value from the array-------
// // // // note it can pop out only last value---

// // // // let array = [" gousia ", " nizam ","salman"," moomin"]
// // // // array.pop("nizam");
// // // // console.log("array after pop out value ");

// // // // console.log(array);

// // // // --------------how to push value in the array ------------

// // // // let array = [" gousia ", " nizam ","salman"," moomin"]
// // // // array.push("javaid");

// // // // console.log(" array after pushing value into  array");

// // // // console.log(array);

// // // // ----------------------substilute hash at vowel place---------------

// // // // let arr = ["a", "b", "c", "d"];

// // // // let vowel = ["a", "e" ,"i", "o", "u"];

// // // // let str = "";

// // // // for (let i = 0; i < arr.length; i++) {
// // // //   let flag = false;
// // // //   for (let j = 0;j < vowel.length; j++) {
// // // //     if (arr[i] === vowel[j]) {
// // // //       flag = true;
// // // //       //   str = str + "#";
// // // //     }
// // // //   }
// // // //   if (flag === true) {
// // // //     str = str + "#";
// // // //   } else {
// // // //     str = str + arr[i];
// // // //   }
// // // // }
// // // // console.log(str);

// // // let arr = [ "a","b","c",]
// // // let vowel =[]
// // // console.log(!false);
// // // if (false) {

// // //     console.log(nizam )
// // // }else{
// // //     console.log(rehman)
// // // }

// // // let i = 1;
// // // let sum = 0;
// // // while (i<=10) {
// // //     sum = sum +i;
// // //     i++;

// // // }console.log(sum);

// // // if (true) { console.log( "excute block");

// // // }else{ console.log(2)};
// // //  let sum = 0;
// // // for(let i =1;i<=10;i++){

// // //    sum = sum + i;
// // //    console.log(sum);

// // //

// // // }
// // // let sum = 0;
// // // let n = 8;
// // // // for(let i =1;i<=10;i++){
// // // // sum = sum + i;
// // // //     // console.log(i);

// // // // }console.log(sum);
// // // if (n%2 === 0) {
// // //   console.log(n+" "+"is a even number ");
// // // } else {
// // //   console.log(n+" "+"is not a even number");
// // // }

// // for(let i = 1;i<=10;i++){
// // if (i%2===0) {
// //     console.log(i+" "+"is a even number");

// // }else{ console.log(n+" "+"is not even");
// // }

// let arr=[1,2,3,4,5]
// // console.log(arr[arr.length-1]);
// for(let i=0; i<=arr.length-1; i++){
//     console.log(arr);

// // }
// let bag =" ";
// for( let x =1;x<=10;x++){
// bag = bag + x+" ";

// }
// console.log(bag)
// let count = 0;
// for(let i= 0;i<=20;i++){
// count++;
// console.log(i);
// console.log(count ,"count");

// }

// //  problem 2
// let arr = [2, 5, 8, 11, 14, 17];
// let sum = 0;

// for (let i = 0; i <= arr.length - 1; i++) {
//   if (arr[i] % 2 == 0) {
//     sum = sum + arr[i];
//   }
// }
// console.log(sum);

// -----------------problem 3----------
// let count = 0;
// let arr = [10, 75, 45, 55, 65, 35];
// for (let i = 0; i < arr.length; i++) {
//   if (arr[i] > 50) {
//     // console.log(arr[i]);
//     count = count + 1;
//   }
// }
// console.log(count);

// ----------- problem 4 ---------

// let arr = [12, 45, 7, 89, 23];
// for (let i = 0; i < arr.length; i++) {
//   if (arr[i] >= 35) {
//     console.log(arr[i], " so pass");
//   } else {
//     console.log(arr[i], "so fail");
//   }
// }

// --------------- problem 5---------------

// let arr = [199, 499, 1299, 99, 599];
// let sum = 0;
// for (let i = 0; i <= arr.length - 1; i++) {
//   if (arr[i] > 100) {
//     sum = sum + arr[i];
//   }
//   if (sum > 1000) {
//     break;
//   }
// }
// console.log(sum);

//--------- problem 1:  (finding sec largest digit in an array)---------

// let arr = [1, 2, 8, 6, 9, 10];
// let max = -Infinity;
// let secmax = -Infinity;

// for (let i = 0; i < arr.length; i++) {
//   if (arr[i] > max) {
//     secmax = max;
//     max = arr[i];
//    } else if (arr[i] > secmax && arr[i] < max) {
//     secmax = arr[i];
//   }
// }console.log(secmax);

function sum(a){
//  a =10
  
    let sum =a*a;
    return sum ;
   
   

}
let result = sum(2);
// console.log(a);

console.log(result);


